version: '3'

services:

  mysqldb:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: helloworld1!
      MYSQL_DATABASE: default_db
    ports:
      - "3306:3306"
    volumes:
      - "./configurations/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"